/*********************************************************************************

** The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ********************************************************************************/

	var alert_arr = {       
            DELETE:'Σίγουρα θέλετε να διαγράψετε τις επιλεγμένες  ',
                                RECORDS:' εγγραφές;',
                                SELECT:'Παρακαλώ επιλέξτε τουλάχιστον μια μονάδα',
                                DELETE_ACCOUNT:'Διαγράφοντας αυτόν τον λογαριασμό(ους) θα διαγραφούν και οι σχετικές ευκαιρίες και προσφορές. Σίγουρα θέλετε να διαγράψετε τις επιλεγμένες ',
                                DELETE_VENDOR:'Διαγράφοντας αυτόν τον προμηθευτή(ές) θα διαγραφούν και οι σχετικές Παραγγελίες Αγοράς. Σίγουρα θέλετε να διαγράψετε τις επιλεγμένες ',
                                SELECT_MAILID:'Παρακαλώ επιλέξτε ένα mailid',
                                OVERWRITE_EXISTING_ACCOUNT1:'Να αντικατασταθεί η υπάρχουσα διεύθυνση με του επιλεγμένου λογαριασμού(',
                                OVERWRITE_EXISTING_ACCOUNT2:') στα στοιχεία διεύθυνσης;',
							    OVERWRITE_EXISTING_CONTACT1:'Να αντικατασταθεί η υπάρχουσα διεύθυνση με της επιλεγμένης επαφής(',
								OVERWRITE_EXISTING_CONTACT2:') στα στοιχεία διεύθυνσης;',                                
								MISSING_FIELDS:'Λείπουν τα απαραίτητα πεδία:',
                                NOT_ALLOWED_TO_EDIT:'δεν επιτρέπεται να αλλάξετε αυτό το πεδίο',
                                COLUMNS_CANNOT_BE_EMPTY:'Ο επιλεγμένες στήλες δεν μπορεί να είναι κενές',
                                CANNOT_BE_EMPTY:' δεν μπορεί να είναι κενά',
                                CANNOT_BE_NONE:' δεν μπορεί να είναι κανένα',
                                ENTER_VALID:'Παρακαλώ εισάγετε ένα έγκυρο ',
                                SHOULDBE_LESS:' θα πρέπει να είναι μικρότερο από ',
                                SHOULDBE_LESS_EQUAL:' θα πρέπει να είναι μικρότερο ή ίσο με ',
                                SHOULDBE_EQUAL:' θα πρέπει να είναι ίσο με ',
                                SHOULDBE_GREATER:' θα πρέπει να είναι μεγαλύτερο από ',
                                SHOULDBE_GREATER_EQUAL:' θα πρέπει να είναι μεγαλύτερο ή ίσο με ',
                                INVALID:'Μη έγκυρο ',
                                EXCEEDS_MAX:' ξεπερνάει το μέγιστο όριο ',
                                OUT_OF_RANGE:' είναι εκτός ορίων',
                                SHOULDNOTBE_EQUAL:' δεν θα πρέπει να είναι ίσο με ',
                                PORTAL_PROVIDE_EMAILID:'Ο χρήστης του Portal θα πρέπει να δώσει το email Id του για να εισέλθει στο portal',
                                ADD_CONFIRMATION:'Σίγουρα θέλετε να προσθέσετε το επιλεγμένο ',
                                ACCOUNTNAME_CANNOT_EMPTY:'Το όνομα λογαριασμού δεν μπορεί να είναι κενό',
                                CANT_SELECT_CONTACTS:'Δεν μπορείτε να επιλέξετε σχετιζόμενες επαφές από τις Συστάσεις',
                                LBL_THIS:'Αυτό ',
                                DOESNOT_HAVE_MAILIDS:' δεν έχει mail ids',
                                ARE_YOU_SURE:'Σίγουρα;',
                                DOESNOT_HAVE_AN_MAILID:'δεν έχει ένα Email Id',
                                MISSING_REQUIRED_FIELDS:'Λείπουν τα απαραίτητα πεδία: ',
                                READONLY:'είναι readonly',
				SELECT_ATLEAST_ONE_USER:'Παρακαλώ επιλέξτε τουλάχιστον ένα χρήστη',
                                DISABLE_SHARING_CONFIRMATION:'Σίγουρα θέλετε να απαγορέψετε την δυνατότητα διαμοιρασμού στον επιλεγμένο ',
                                USERS:' χρήστη(ες);',
                                ENDTIME_GREATER_THAN_STARTTIME:'Ο Χρόνος Λήξης θα πρέπει να είναι μεγαλύτερος του Χρόνου Έναρξης ',
                                FOLLOWUPTIME_GREATER_THAN_STARTTIME:'Ο Χρόνος Επανεξέτασης θα πρέπει να είναι μεγαλύτερος του Χρόνου Λήξης ',
                                MISSING_EVENT_NAME:'Λείπει το όνομα του Γεγονότος',
                                EVENT_TYPE_NOT_SELECTED:'Δεν έχει επιλεγεί ο τύπος του Γεγονότος',
                                OPPORTUNITYNAME_CANNOT_BE_EMPTY:'Το πεδίο ονόματος Ευκαιρίας δεν μπορεί να είναι κενό',
				NAME_DESC:' για το όνομα Φακέλου & Περιγραφή'                                
				CLOSEDATE_CANNOT_BE_EMPTY:'Το πεδίο Ημερομηνίας Κλεισίματος δεν μπορεί να είναι κενό',
                                SITEURL_CANNOT_BE_EMPTY:'Το Site Url δεν μπορεί να είναι κενό',
                                SITENAME_CANNOT_BE_EMPTY:'Το Site Name δεν μπορεί να είναι κενό',
                                LISTPRICE_CANNOT_BE_EMPTY:'Η τιμή τιμοκαταλόγου δεν μπορεί να είναι κενή',
                                INVALID_LIST_PRICE:'Μή έγκυρη τιμή τιμοκαταλόγου',
                                PROBLEM_ACCESSSING_URL:'Πρόβλημα κατά το άνοιγμα του url: ',
                                CODE:' Κωδικός: ',
                                WISH_TO_QUALIFY_MAIL_AS_CONTACT:'Σίγουρα θέλετε να μετατρέψετε αυτό το Mail σε επαφή;',
                                SELECT_ATLEAST_ONEMSG_TO_DEL:'Παρακαλώ επιλέξτε τουλάχιστον ένα μήνυμα για να διαγράψετε',
                                ERROR:'Σφάλμα',
                                FIELD_TYPE_NOT_SELECTED:'Ο τύπος πεδίου δεν έχει επιλεγεί',
                                SPECIAL_CHARACTERS_NOT_ALLOWED:'Δεν επιτρέπονται σε αυτό το πεδίο Ειδικοί χαρακτήρες',
								SPECIAL_CHARACTERS:'Ειδικοί χαρακτήρες',
								NOT_ALLOWED:'δεν επιτρέπονται. Παρακαλούμε δοκιμάστε άλλες τιμές',                                
								PICKLIST_CANNOT_BE_EMPTY:'Η τιμή αυτή δεν μπορεί να είναι κενή',
                                DUPLICATE_VALUES_FOUND:'Βρέθηκαν διπλοεγγραφές στις τιμές',
                                DUPLICATE_MAPPING_ACCOUNTS:'Διπλοαντιστοίχιση Λογαριασμών!!',
                                DUPLICATE_MAPPING_CONTACTS:'Διπλοαντιστοίχιση Επαφών!!',
                                DUPLICATE_MAPPING_POTENTIAL:'Διπλοαντιστοίχιση Ευκαιριών!!',
                                ERROR_WHILE_EDITING:'Σφάλμα κατά την επεξεργασία',
								CURRENCY_CHANGE_INFO:'Η αλλαες στο Νόμισμα έγιναν Επιτυχώς',                               
								CURRENCY_CONVERSION_INFO:'Χρησιμοποιείτε το  δολλάριο $ ως νόμισμα; \n Πατήστε το OK για να παραμείνει ως $, ή Ακύρωση για να αλλάξετε την τιμή συναλλάγματος.',
                                THE_EMAILID: "Το email id \'",
                                EMAIL_FIELD_INVALID:"\' στο πεδίο email δεν είναι έγκυρο",
                                MISSING_REPORT_NAME:'Λείπει το όνομα της αναφοράς',
                                REPORT_NAME_EXISTS:'Το όνομα της αναφοράς υπάρχει ήδη, προσπαθήστε ξανά...',
                                WANT_TO_CHANGE_CONTACT_ADDR:'Θέλετε να αλλάξετε τις διευθύνσεις των επαφών που σχετίζονται με αυτό το λογαριασμό;',
                                SURE_TO_DELETE:'Σίγουρα θέλετε να διαγράψετε;',
				NO_PRODUCT_SELECTED:'Δεν έχει επιλεγεί προϊόν. Επιλέξτε τουλάχιστον ένα Προϊόν.',
                                VALID_FINAL_PERCENT:'Εισάγετε έγκυρο Τελικό Ποσοστό Έκπτωσης',
                                VALID_FINAL_AMOUNT:'Εισάγετε έγκυρο Τελικό Ποσό Έκπτωσης',
                                VALID_SHIPPING_CHARGE:'Είσάγετε  έγκυρη χρέωση Συσκευασίας και Αποστολής',
                                VALID_ADJUSTMENT:'Εισάγετε μια έγκυρη Διόρθωση',
                                WANT_TO_CONTINUE:'Θέλετε να συνεχίσετε;',
                                ENTER_VALID_TAX:'Παρακαλώ εισάγετε έγκυρο Ποσό Φόρου',
                                VALID_TAX_NAME:'Εισάγετε έγκυρη Ονομασία Φόρου',
                                CORRECT_TAX_VALUE:'Εισάγετε σωστή Αξία Φόρου',
                                ENTER_POSITIVE_VALUE:'Παρακαλώ εισάγετε Θετική Αξία',
                                LABEL_SHOULDNOT_EMPTY:'Δεν μπορεί να είναι κενό το όνομα του φόρου',
                                NOT_VALID_ENTRY:'δεν είναι μια έγκυρη εγγραφή. Παρακαλώ εισάγετε σωστή τιμή',
                                VALID_DISCOUNT_PERCENT:'Εισάγετε έγκυρο ποσοστό Έκπτωσης',
                                VALID_DISCOUNT_AMOUNT:'Εισάγετε έγκυρο Ποσό έκπτωσης',
                                SELECT_TEMPLATE_TO_MERGE:'Παρακαλώ επιλέξτε Πρότυπο για Συγχώνευση',
				SELECTED_MORE_THAN_ONCE:'Έχετε επιλέξει τα ακόλουθα προϊόντα περισσότερες από μία φορές.',
				YES:'ναι',
                                NO:'όχι',
                                MAIL:'mail',
		 		EQUALS:'είναι ίσο με',
				NOT_EQUALS_TO:'δεν είναι ίσο με',
				STARTS_WITH:'ξεκινάει με',
				CONTAINS:'περιέχει',	
				DOES_NOT_CONTAINS:'δεν περιέχει',
				LESS_THAN:'μικρότερο από',
				GREATER_THAN:'μεγαλύτερο από',
				LESS_OR_EQUALS:'μικρότερο ή ίσο',
				GREATER_OR_EQUALS:'μεγαλύτερο ή ίσο',

				NO_SPECIAL_CHARS:'Δεν επιτρέπονται οι ειδικοί χαρακτήρες στο String Τιμολογίου',
				ENDS_WITH:'λήγει με'				
				SHARED_EVENT_DEL_MSG:'Αυτός ο χρήστης δεν έχει δικαίωμα να διαγράψει αυτή την εγγραφή.',
				PLS_SELECT_VALID_FILE:'Παρακαλώ επιλέξτε αρχείο με την ακόλουθη επέκταση:\n',
                                NO_SPECIAL:'Δεν επιτρέπονται ειδικοί χαρακτήρες',
				IN_PROFILENAME:' στο Όνομα του Προφίλ',
				IN_GROUPNAME:' στο Όνομα της Ομάδας',
				IN_ROLENAME:' στο Όνομα του Ρόλου',
                                VALID_TAX_PERCENT:'Εισάγετε έγκυρο ποσοστό φόρου',
                                VALID_SH_TAX:'Εισάγετε έγκυρο φόρο για Συσκευασία και Αποστολή ',
				ROLE_DRAG_ERR_MSG:'Δεν μπορείτε να μετακινήσετε Γονικό Κόμβο κάτω από Θυγατρικό',
				LBL_DEL:'διαγ',
				VALID_DATA :' Εισάγετε έγκυρα στοιχεία. Προσπαθήστε ξανά... ',
                                STDFILTER : 'Καθιερωμένα Φίλτρα',
                                STARTDATE : 'Ημερομηνία Έναρξης',
                                ENDDATE : 'Ημερομηνία Λήξης',
                                START_DATE_TIME : 'Ημερομηνία & Ώρα Έναρξης',
                                START_TIME : 'Ώρα Έναρξης',
                                DATE_SHOULDNOT_PAST :'Ισχύουσα Ημερομηνία και Ώρα για Δραστηριότητες σε κατάσταση Καθορισμένες',
                                TIME_SHOULDNOT_PAST :'Ισχύουσα Ώρα για Δραστηριότητες σε κατάσταση Καθορισμένες',
				LBL_AND : 'και',
				LBL_ENTER_VALID_PORT: 'Παρακαλώ εισάγετε έγκυρο αριθμό πόρτας',
				IN_USERNAME :' στο όνομα Χρήστη ',
				LBL_ENTER_VALID_NO: 'Παρακαλώ εισάγετε έγκυρο αριθμό',
				LBL_PROVIDE_YES_NO: ' Μή έγκυρη τιμή.\n Παρακαλώ επιλέξτε Ναι ή Όχι',
				LBL_SELECT_CRITERIA: ' Μή έγκυρα κριτήρια.\n Παρακαλώ επιλέξτε κριτήρια',
				LBL_WRONG_IMAGE_TYPE: 'Επιτρεπτοί τύποι αρχείων για τις επαφές - jpeg, png, jpg, pjpeg, x-png ή gif',
				SELECT_MAIL_MOVE: 'Παρακαλώ επιλέξτε ένα mail και μετά μετακινείστε..',
				LBL_NOTSEARCH_WITHSEARCH_ALL:'Δεν χρησιμοποιήσατε την αναζήτηση. Όλες οι εγγραφές θα εξαχθούν από  ',
				LBL_NOTSEARCH_WITHSEARCH_CURRENTPAGE:'Δεν κάνατε αναζήτηση. Όμως επιλέξατε με αναζήτηση και επιλογές της παρούσας σελίδας. Έτσι οι εγγραφές στην παρούσα σελίδα θα εξαχθούν από ',
				LBL_NO_DATA_SELECTED:'Δεν έχει επιλεγεί εγγραφή. Επιλέξτε τουλάχιστον μια εγγραφή για να εξάγετε',
				LBL_SEARCH_WITHOUTSEARCH_ALL:'Έχετε χρησιμοποιήσει την επιλογή αναζήτησης αλλά δεν έχετε επιλέξει χωρίς αναζήτηση και όλες οι επιλογές. \n Μπορείτε να πατήσετε [ΟΚ] για να εξάγετε όλα τα δεδομένα ή μπορείτε να πατήσετε [Ακύρωση] για να δοκιμάσετε ξανά με άλλα κριτήρια αναζήτησης',
				STOCK_IS_NOT_ENOUGH : 'Το στοκ δεν επαρκεί',
				INVALID_QTY : 'Μή έγκυρη ποσότητα',
				LBL_SEARCH_WITHOUTSEARCH_CURRENTPAGE:'Έχετε χρησιμοποιήσει την επιλογή αναζήτησης αλλά δεν έχετε επιλέξει χωρίς αναζήτηση και οι επιλογές της παρούσας σελίδας. \n Μπορείτε να πατήσετε [ΟΚ] για να εξάγετε τα δεδομένα της παρούσας σελίδας ή μπορείτε να πατήσετε [Ακύρωση] για να δοκιμάσετε ξανά με άλλα κριτήρια εξαγωγής.',
				LBL_SELECT_COLUMN: ' Μή έγκυρη στήλη.\n Παρακαλώ επιλέξτε στήλη',
				LBL_NOT_ACCESSIBLE : 'Μή προσβάσιμο',
				LBL_FILENAME_LENGTH_EXCEED_ERR: 'Το όνομα αρχείου δεν μπορεί να ξεπερνάει τους 255 χαρακτήρες',
				LBL_DONT_HAVE_EMAIL_PERMISSION : 'Δεν έχετε δικαιώματα στο πεδίο Email κι έτσι δεν μπορείτε να επιλέξετε το email id',
				LBL_NO_FEEDS_SELECTED: 'Δεν έχουν επιλεγεί Feeds',
				LBL_SELECT_PICKLIST:'Παρακαλώ επιλέξτε τουλάχιστον μια τιμή για να διαγράψετε',
				LBL_CANT_REMOVE:'Δεν μπορείτε να αφαιρέσετε όλες τις τιμές',

				// Added after 5.0.4 GA
				
				/*For global add/delete in picklist*/
				LBL_GIVE_PICKLIST_VALUE:'Please provide some value for the selected picklist to be replaced',
				LBL_SELECT_ROLE:'Please select atleast one role for which the new values are to be added',
				LBL_ADD_PICKLIST_VALUE:'Please provide atleast one new value to be added',
				LBL_NO_VALUES_TO_DELETE: "no values to delete",

                /* For Duplicate merging feature */
				SAME_GROUPS: 'You have to select the records in the same groups for merging',
				ATLEAST_TWO: 'Select atleast two records for merging',
				MAX_THREE: 'You are allowed to select a maximum of three records',
				//PARENT_RECORD: 'Select a record as parent record',  MergeFields.tpl Line:59
				MAX_RECORDS: 'You are allowed to select a maximum of four records',
				CON_MANDATORY: 'Select the mandatory field Last Name',
				LE_MANDATORY: 'Select the mandatory fields Last Name and Company',
				ACC_MANDATORY: 'Select the mandatory field Account Name',
				PRO_MANDATORY: 'Select the mandatory field Product Name',
				TIC_MANDATORY: 'Select the mandatory field Ticket Title',
				POTEN_MANDATORY: 'Select the mandatory field Potential Name',
				VEN_MANDATORY: 'Select the mandatory field Vendor Name',
				DEL_MANDATORY: 'You are not allowed to delete the mandatory field',
				
				/* For Multi-Currency Support */
				MSG_CHANGE_CURRENCY_REVISE_UNIT_PRICE: 'Unit price of all the Currencies will be revised based on the selected Currency. Are you sure?',
				
				Select_one_record_as_parent_record : 'Select one record as parent record',
				RECURRING_FREQUENCY_NOT_PROVIDED : 'Recurring frequency not provided',
				RECURRING_FREQNECY_NOT_ENABLED : 'Recurring frequency is provided, but recurring is not enabled',
				/* Added for Documents module */
				NO_SPECIAL_CHARS_DOCS:'Special characters like quotes, backslash, + symbol, % and ? are not allowed',
				FOLDER_NAME_TOO_LONG:'Folder name is too long. Try again!',
				FOLDERNAME_EMPTY:'The Folder name cannot be empty',
				DUPLICATE_FOLDER_NAME:'Trying to duplicate an existing folder name. Please try again !',
				FOLDER_DESCRIPTION_TOO_LONG:'Folder description is too long. Try again!',
				NOT_PERMITTED:"You are not permitted to execute this operation.",		
				
				ALL_FILTER_CREATION_DENIED:'Cannot create CustomView using name "All", try using different ViewName',
				OPERATION_DENIED:'You are denied to perform this operation',
				EMAIL_CHECK_MSG: 'Disable portal access to save the email field as blank',
				IS_PARENT : 'This Product has Sub Products, You are not allowed to choose a Parent for this Product',
				
				/*global actions on picklist*/
				PICKLIST_CANNOT_BE_EMPTY: 'Picklist value cannot be empty',
				DUPLICATE_VALUES_FOUND: 'Duplicate Values found',
				LBL_NO_ROLES_SELECTED: 'No roles have been selected, do you wish to continue?',
				LBL_DUPLICATE_FOUND: 'Duplicate entries found for the value ',
				LBL_CANNOT_HAVE_EMPTY_VALUE: 'Cannot replace with blank value, to remove the value use Delete option.',
				LBL_DUPLICATE_VALUE_EXISTS: 'Duplicate value exists',
				LBL_WANT_TO_DELETE: "This will delete the selected picklist value(s) for all roles. You sure you want to continue? ",
				LBL_DELETE_ALL_WARNING: "Must have atleast one value for the picklist",
				LBL_PLEASE_CHANGE_REPLACEMENT: "please change the replacement value; it is also selected for delete",
				
				/*layout Editor changes*/
				BLOCK_NAME_CANNOT_BE_BLANK : 'Block name can not be blank',
				ARE_YOU_SURE_YOU_WANT_TO_DELETE : 'Are you sure you want to delete ?',
				PLEASE_MOVE_THE_FIELDS_TO_ANOTHER_BLOCK : 'Please move the fields to another block',
				ARE_YOU_SURE_YOU_WANT_TO_DELETE_BLOCK : 'Are you sure you want to delete block?',
				LABEL_CANNOT_NOT_EMPTY : 'Label cannot be Emtpy',
				LBL_TYPEALERT_1 : 'Sorry, you cannot map the',
				LBL_WITH : 'with',
				LBL_TYPEALERT_2 : 'data type. Kindly map the same data types.',
				LBL_LENGTHALERT : 'Sorry, you can cannot map fields with different character size. Kindly map the data with same or more character size.',
				LBL_DECIMALALERT : 'Sorry, you can cannot map fields with different decimal places. Kindly map the data with same or more decimal places.',
				FIELD_IS_MANDATORY : 'Mandatory Field',
				FIELD_IS_ACTIVE : 'Field is available for use',
				FIELD_IN_QCREATE : 'Present in Quick Create',
				FIELD_IS_MASSEDITABLE : 'Available for Mass Edit',	
					
				IS_MANDATORY_FIELD : 'is Mandatory Field',
				CLOSEDATE_CANNOT_BE_EMPTY : 'Closing Date cannot be Empty',
				AMOUNT_CANNOT_BE_EMPTY : 'Amount cannot be Empty',
				ARE_YOU_SURE : 'Are You Sure You want to Delete?',
				LABEL_ALREADY_EXISTS : 'Label already exists. Please specify a different Label',
				LENGTH_OUT_OF_RANGE : 'Length of the Block should be less than 50 characters',
				LBL_SELECT_ONE_FILE : 'Please select atleast one File',
				LBL_UNABLE_TO_ADD_FOLDER : 'Unable to add Folder. Please try again.',
				LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE_FOLDER : 'Are you sure you want to delete the folder?',
				LBL_ERROR_WHILE_DELETING_FOLDER : 'Error while deleting the folder.Please try again later.',
				LBL_FILE_CAN_BE_DOWNLOAD : 'File is available for download',
				LBL_DOCUMENT_LOST_INTEGRITY:'This Documents is not available. It will be marked as Inactive',
				LBL_DOCUMENT_NOT_AVAILABLE : 'This Document is not available for Download',
				LBL_FOLDER_SHOULD_BE_EMPTY : 'Folder should be empty to remove it!',
				
				LBL_PLEASE_SELECT_FILE_TO_UPLOAD : 'Please select the file to upload.',
				LBL_ARE_YOU_SURE_TO_MOVE_TO : 'Are you sure you want to move the file(s) to ',
				LBL_FOLDER : ' folder',
				LBL_UNABLE_TO_UPDATE : 'Unable to update! Please try it again.',
				LBL_BLANK_REPLACEMENT: "Cannot select blank value for replacement",
				
				LBL_IMAGE_DELETED : 'Image Deleted',
				
				/* Tooltip management */
				ERR_FIELD_SELECTION : 'Some error in field selection',
				
				/* Inventory validation strings */
				NO_LINE_ITEM_SELECTED : 'No line item is selected. Please select at least one line item.',
				LINE_ITEM : 'Line item',
				LIST_PRICE: 'List Price',
				
				/* Webmails */
				LBL_PRINT_EMAIL : 'Print', 
				LBL_DELETE_EMAIL : 'Delete', 
				LBL_DOWNLOAD_ATTACHMENTS : 'Download Attachments', 
				LBL_QUALIFY_EMAIL : 'Qualify', 
				LBL_FORWARD_EMAIL : 'Forward', 
				LBL_REPLY_TO_SENDER : 'Reply To Sender', 
				LBL_REPLY_TO_ALL : 'Reply To All',
				
				LBL_WIDGET_HIDDEN : 'Widget Hidden',
				LBL_RESTORE_FROM_PREFERENCES : 'You can restore it from your preferences',
				ERR_HIDING : 'Error while hiding',
				MSG_TRY_AGAIN : 'Please try again',
				
				MSG_ENABLE_SINGLEPANE_VIEW : 'Singlepane View Enabled',
				MSG_DISABLE_SINGLEPANE_VIEW : 'Singlepane View Disabled',
				
				MSG_FTP_BACKUP_DISABLED : 'FTP Backup Disabled',
				MSG_LOCAL_BACKUP_DISABLED : 'Local Backup Disabled',
				MSG_FTP_BACKUP_ENABLED : 'FTP Backup Enabled',
				MSG_LOCAL_BACKUP_ENABLED : 'Local Backup Enabled',
				MSG_CONFIRM_PATH : 'confirm with the Path details',
				MSG_CONFIRM_FTP_DETAILS : 'confirm with the FTP details',
				
				START_PERIOD_END_PERIOD_CANNOT_BE_EMPTY : 'Start period or End period cannot be empty',
				
				/* added to fix i18n issues with home page*/
				LBL_ADD: 'Add ',
				Module: 'Module',
				DashBoard: 'DashBoard',
				RSS: 'RSS',
				Default: 'Default',
				Notebook: 'Notebook',
				SPECIAL_CHARS:'\\ / < > + \' " ',

	'BETWEEN': 'between',
	'BEFORE': 'before',
	'AFTER': 'after',
	'ERROR_DELETING_TRY_AGAIN': 'Error while deleting.Please try again.',
	'LBL_ENTER_WINDOW_TITLE': 'Please enter Window Title.',
	'LBL_SELECT_ONLY_FIELDS': 'Please select only two fields.',
	'LBL_ENTER_RSS_URL':'Please enter RSS URL',
	'LBL_ADD_HOME_WIDGET': 'Unable to add homestuff! Please try again',

	'LBL_DEFAULT_VALUE_FOR_THIS_FIELD' : 'Default Value for this Field',

	'RECIPIENTS_CANNOT_BE_EMPTY' : 'Selected Recipients cannot be empty',
	'VALID_SCANNER_NAME' : 'Please enter a valid Scanner name (It should be only Characters and Numbers)',
	'ERR_SAME_SOURCE_AND_TARGET' : 'Source field and Target field should not be same',
	'ERR_ATLEAST_ONE_VALUE_FOR' : 'You need to select at least one value for',
	'ERR_SELECT_MODULE_FOR_DEPENDENCY' : 'Please select a module to add Dependency',

	'LBL_SIZE_SHOULDNOTBE_GREATER':'File size should not be greater than ', //added for upload error message
	'LBL_MAX_SIZE':'Μέγιστο επιτρεπτό μέγεθος επισύναψης είναι', //added for display file size limit
	'LBL_FILESIZEIN_MB':'MB', // added to show filesize limit in MB
	'LBL_FILESIZEIN_KB':'KB', // added to show filesize limit in KB
	'LBL_FILESIZEIN_B':'B', // added to show filesize limit in B
	//Contexual help page
    'LBL_HELP_TITLE' : 'Help',
    'LBL_WIKI_TITLE' : 'Manuals',
    'LBL_FAQ_TITLE'   : 'FAQ',
    'LBL_VIDEO_TITLE' : 'Video',
    'LBL_CLOSE_TITLE' : 'Close',
	'LBL_SELECT':'Select Default Widgets To Be Shown',

	'ERR_SELECT_ATLEAST_ONE_MERGE_CRITERIA_FIELD' : 'Select at least one field for merge criteria',
	'ERR_PLEASE_MAP_MANDATORY_FIELDS' : 'Please map the following mandatory fields',
	'ERR_MAP_NAME_ALREADY_EXISTS' : 'Map name already exists. Please give a different name',
	'ERR_MAP_NAME_CANNOT_BE_EMPTY' : 'Map name cannot be empty',
	'ERR_FIELDS_MAPPED_MORE_THAN_ONCE' : 'Following field is mapped more than once. Please check the mapping.',

	//arror messages for lead conversion
	'ERR_SELECT_EITHER':'Select either Organization or Contact to convert the lead',
	'ERR_SELECT_ACCOUNT':'Select Organization to proceed',
	'ERR_SELECT_CONTACT':'Select Contact to proceed',
	'ERR_MANDATORY_FIELD_VALUE':'Values for Mandatory Fields are missing',
	'ERR_POTENTIAL_AMOUNT':'Potential Amount must be a number',
	'ERR_EMAILID':'Enter valid Email Id',
	'ERR_TRANSFER_TO_ACC':'Organization should be selected to transfer related records',
	'ERR_TRANSFER_TO_CON':'Contact should be selected to transfer related records ',
	'SURE_TO_DELETE_CUSTOM_MAP':'Are you sure you want to delete the Field Mapping?',
	'LBL_CLOSE_DATE':'Close Date',
	'LBL_EMAIL':'Email',
	'MORE_THAN_500' : 'You selected more than 500 records. For this action it may take longer time. Are you sure want to proceed?',
	'LBL_MAPPEDALERT':'The field has been already mapped',

     };
